CHUACHONHANVAT = "Chưa chọn nhân vật"
IDKYNANGCAONHATCOTHESUDUNG = 512
SOLUONGNHANVATTOIDA = 1024
SOLUONGVATPHAMTOIDA = 512
SOLUONGVITRIVATPHAMTOIDA = 1024
SOLUONGVATPHAMTOIDADUOIDAT = 512
SOLUONGKYNANGTOIDA = 512
SOHANHTRANGTOIDA = 3

VITRIRUONGDANGCAMTRENTAY = 1
VITRIRUONGTRANGBI = 2
VITRIRUONGHANHTRANG = 3
VITRIRUONGTHUKHO1 = 4

DINGOAIPHUSIEUCAP = "Di ngoại phù (Siêu cấp)"
HOITHANHPHUSIEUCAP = "Hồi thành phù (Siêu cấp)"
KHULAIPHU = "Khứ Lai phù"
TIENDONG = "Tiền đồng"
MATQUY = "Mặt Quỷ"
HOAVU = "Hỏa vũ"
BANGCO = "Băng cơ"
NGOCCOT = "Ngọc cốt"
DOANKIEM = "Đoản Kiếm"
MANHGIAP = "Mảnh Giáp"
THANHLO = "Thanh Lộ"
CHANKHI = "Chân Khí"
THANHLOTIEU = "Thanh Lộ (tiểu)"
CHANKHITIEU = "Chân Khí (tiểu)"
DINGOAIPHU = "Di ngoại phù"
TUIMANHPHAPBAOCAP10 = "Túi mảnh Pháp Bảo cấp 10"
TUIMANHPHAPBAOCAP30 = "Túi mảnh Pháp Bảo cấp 30"
TUIMANHPHAPBAOCAP50 = "Túi mảnh Pháp Bảo cấp 50"
TUIMANHPHAPBAOCAP70 = "Túi mảnh Pháp Bảo cấp 70"

VATPHAMKHONGBANs = (
    HOITHANHPHUSIEUCAP, DINGOAIPHUSIEUCAP, KHULAIPHU, TIENDONG, MATQUY, HOAVU, BANGCO, NGOCCOT, DOANKIEM, MANHGIAP, THANHLO, THANHLOTIEU, CHANKHI, CHANKHITIEU, DINGOAIPHU,
    TUIMANHPHAPBAOCAP10, TUIMANHPHAPBAOCAP30, TUIMANHPHAPBAOCAP50, TUIMANHPHAPBAOCAP70
)

XIVUUMO = "Xi Vưu Mộ"
NGOCHUCUNG = "Ngọc Hư cung"

CHANNOICONLON = "Chân núi Côn Lôn"

CULOC = "Cự Lộc"
DUHON = "Du Hồn"

TOADODAIPHU_MAP = {
    NGOCHUCUNG: (56303, 103147),
    XIVUUMO: (50020, 103760),
}

TOADODIEMCHUYENTIEP_MAP = {
    (XIVUUMO, XIVUUMO): (45718, 100250),
    (XIVUUMO, DUHON): (45718, 100250),
    (XIVUUMO, CULOC): (55624, 104258),

    (NGOCHUCUNG, NGOCHUCUNG): (57099, 104598),
    (NGOCHUCUNG, CHANNOICONLON): (57099, 104598),
}

BANDO_IDLOAIVATPHAMBIENPHU_VITRI_MAP = {
    "Tây Kỳ": (DINGOAIPHUSIEUCAP, "2"),
    "Sùng Thành": (DINGOAIPHUSIEUCAP, "7"),
    "Bắc Hải": (DINGOAIPHUSIEUCAP, "8"),
    "Yến Sơn": (DINGOAIPHUSIEUCAP, "9"),
    "Chân Núi Côn Lôn": (DINGOAIPHUSIEUCAP, "10"),
    "Tây Côn Lôn": (DINGOAIPHUSIEUCAP, "11"),
    "Thủ Dương Sơn": (DINGOAIPHUSIEUCAP, "12"),
    DUHON: (DINGOAIPHUSIEUCAP, "13"),
    "Miêu Cương": (DINGOAIPHUSIEUCAP, "14"),
    CULOC: (DINGOAIPHUSIEUCAP, "15"),
    "Đồng Quan": (DINGOAIPHUSIEUCAP, "16|0"),
    "Mạnh Tân": (DINGOAIPHUSIEUCAP, "16|1"),
    "Tam Sơn": (DINGOAIPHUSIEUCAP, "16|2"),
    "Kỳ Sơn": (DINGOAIPHUSIEUCAP, "16|3"),
    "Mục Dã": (DINGOAIPHUSIEUCAP, "16|4"),
    "Tuyệt Long Lĩnh": (DINGOAIPHUSIEUCAP, "16|5"),
    "Trần Đường": (DINGOAIPHUSIEUCAP, "16|6"),
}

PHAMCHATVATPHAM_TRANGLAM = 0
PHAMCHATVATPHAM_LUC = 1
PHAMCHATVATPHAM_VANG = 2
PHAMCHATVATPHAM_CAM = 3

PHAMCHATVATPHAM_MAP = {
    PHAMCHATVATPHAM_TRANGLAM: "Trắng/Lam",
    PHAMCHATVATPHAM_LUC: "Lục",
    PHAMCHATVATPHAM_VANG: "Vàng",
    PHAMCHATVATPHAM_CAM: "Cam"
}

DANHMUCTRANGBI_VUKHI = 0
DANHMUCTRANGBI_AO = 2
DANHMUCTRANGBI_PHAPBAO = 4
DANHMUCTRANGBI_GIAY = 5
DANHMUCTRANGBI_DAI = 6
DANHMUCTRANGBI_NON = 7
DANHMUCTRANGBI_PHIPHONG = 9
DANHMUCTRANGBI_THUCUOI = 10

DANHMUCTRANGBI_MAP = {
    DANHMUCTRANGBI_VUKHI: "Vũ khí",
    DANHMUCTRANGBI_AO: "Áo",
    DANHMUCTRANGBI_PHAPBAO: "Pháp bảo",
    DANHMUCTRANGBI_GIAY: "Giày",
    DANHMUCTRANGBI_DAI: "Đai",
    DANHMUCTRANGBI_NON: "Nón",
    DANHMUCTRANGBI_PHIPHONG: "Phi phong",
    DANHMUCTRANGBI_THUCUOI: "Thú cưỡi"
}

DANHMUCVATTUTIEUHAO_TRANGBI = 0


THUOCTINHVATPHAM_GIAMTRUNGTHUONG = 113
THUOCTINHVATPHAM_GIAMDONGBANG = 106
THUOCTINHVATPHAM_XUATCHIEUVUKHI = 115
THUOCTINHVATPHAM_XUATCHIEUBUAPHAP = 116
THUOCTINHVATPHAM_DANHTAPTRUNG = 146
THUOCTINHVATPHAM_BANGSAT = 123
THUOCTINHVATPHAM_STCBCONGTHEM = 121

TENTHUOCTINH_MAP = {
    THUOCTINHVATPHAM_GIAMTRUNGTHUONG: "Giảm trúng thương",
    THUOCTINHVATPHAM_GIAMDONGBANG: "Giảm đóng băng",
    THUOCTINHVATPHAM_XUATCHIEUVUKHI: "Xuất chiêu vũ khí",
    THUOCTINHVATPHAM_XUATCHIEUBUAPHAP: "Xuất chiêu bùa pháp",
    THUOCTINHVATPHAM_DANHTAPTRUNG: "Đánh tập trung",
    THUOCTINHVATPHAM_BANGSAT: "Băng sát",
    THUOCTINHVATPHAM_STCBCONGTHEM: "STCB cộng thêm",
}
