CHUACHONHANVAT = "Chưa chọn nhân vật"
IDKYNANGCAONHATCOTHESUDUNG = 512
SOLUONGNHANVATTOIDA = 1024
SOLUONGVATPHAMTOIDA = 512
SOLUONGVITRIVATPHAMTOIDA = 1024
SOLUONGVATPHAMTOIDADUOIDAT = 512
SOLUONGKYNANGTOIDA = 512
SOHANHTRANGTOIDA = 3

VITRIRUONGDANGCAMTRENTAY = 1
VITRIRUONGTRANGBI = 2
VITRIRUONGHANHTRANG = 3
VITRIRUONGTHUKHO1 = 4

DINGOAIPHUSIEUCAP = "Di ngoại phù (Siêu cấp)"
HOITHANHPHUSIEUCAP = "Hồi thành phù (Siêu cấp)"
KHULAIPHU = "Khứ Lai phù"
TIENDONG = "Tiền đồng"
MATQUY = "Mặt Quỷ"
HOAVU = "Hỏa vũ"
BANGCO = "Băng cơ"
NGOCCOT = "Ngọc cốt"
DOANKIEM = "Đoản Kiếm"
MANHGIAP = "Mảnh Giáp"
THANHLO = "Thanh Lộ"
CHANKHI = "Chân Khí"
THANHLOTIEU = "Thanh Lộ (tiểu)"
CHANKHITIEU = "Chân Khí (tiểu)"
DINGOAIPHU = "Di ngoại phù"
TUIMANHPHAPBAOCAP10 = "Túi mảnh Pháp Bảo cấp 10"
TUIMANHPHAPBAOCAP30 = "Túi mảnh Pháp Bảo cấp 30"
TUIMANHPHAPBAOCAP50 = "Túi mảnh Pháp Bảo cấp 50"
TUIMANHPHAPBAOCAP70 = "Túi mảnh Pháp Bảo cấp 70"

VATPHAMKHONGBANs = (
    HOITHANHPHUSIEUCAP, DINGOAIPHUSIEUCAP, KHULAIPHU, TIENDONG, MATQUY, HOAVU, BANGCO, NGOCCOT, DOANKIEM, MANHGIAP, THANHLO, THANHLOTIEU, CHANKHI, CHANKHITIEU, DINGOAIPHU,
    TUIMANHPHAPBAOCAP10, TUIMANHPHAPBAOCAP30, TUIMANHPHAPBAOCAP50, TUIMANHPHAPBAOCAP70
)

XIVUUMO = "Xi Vưu Mộ"
NGOCHUCUNG = "Ngọc Hư cung"

CHANNOICONLON = "Chân núi Côn Lôn"

CULOC = "Cự Lộc"
DUHON = "Du Hồn"

TOADODAIPHU_MAP = {
    NGOCHUCUNG: (56303, 103147),
    XIVUUMO: (50020, 103760),
}

TOADODIEMCHUYENTIEP_MAP = {
    (XIVUUMO, XIVUUMO): (45718, 100250),
    (XIVUUMO, DUHON): (45718, 100250),
    (XIVUUMO, CULOC): (55624, 104258),

    (NGOCHUCUNG, NGOCHUCUNG): (57108, 104648),
    (NGOCHUCUNG, CHANNOICONLON): (57108, 104648),
}

BANDO_IDLOAIVATPHAMBIENPHU_VITRI_MAP = {
    "Tây Kỳ": (DINGOAIPHUSIEUCAP, "2"),
    "Sùng Thành": (DINGOAIPHUSIEUCAP, "7"),
    "Bắc Hải": (DINGOAIPHUSIEUCAP, "8"),
    "Yến Sơn": (DINGOAIPHUSIEUCAP, "9"),
    "Chân Núi Côn Lôn": (DINGOAIPHUSIEUCAP, "10"),
    "Tây Côn Lôn": (DINGOAIPHUSIEUCAP, "11"),
    "Thủ Dương Sơn": (DINGOAIPHUSIEUCAP, "12"),
    DUHON: (DINGOAIPHUSIEUCAP, "13"),
    "Miêu Cương": (DINGOAIPHUSIEUCAP, "14"),
    CULOC: (DINGOAIPHUSIEUCAP, "15"),
    "Đồng Quan": (DINGOAIPHUSIEUCAP, "16|0"),
    "Mạnh Tân": (DINGOAIPHUSIEUCAP, "16|1"),
    "Tam Sơn": (DINGOAIPHUSIEUCAP, "16|2"),
    "Kỳ Sơn": (DINGOAIPHUSIEUCAP, "16|3"),
    "Mục Dã": (DINGOAIPHUSIEUCAP, "16|4"),
    "Tuyệt Long Lĩnh": (DINGOAIPHUSIEUCAP, "16|5"),
    "Trần Đường": (DINGOAIPHUSIEUCAP, "16|6"),
}

IDPHAMCHATVATPHAM_TRANGLAM = 0
IDPHAMCHATVATPHAM_LUC = 1
IDPHAMCHATVATPHAM_VANG = 2
IDPHAMCHATVATPHAM_CAM = 3

PHAMCHATVATPHAM_MAP = {
    IDPHAMCHATVATPHAM_TRANGLAM: "Trắng/Lam",
    IDPHAMCHATVATPHAM_LUC: "Lục",
    IDPHAMCHATVATPHAM_VANG: "Vàng",
    IDPHAMCHATVATPHAM_CAM: "Cam"
}

IDDANHMUCTRANGBI_VUKHI = 0
IDDANHMUCTRANGBI_AO = 2
IDDANHMUCTRANGBI_PHAPBAO = 4
IDDANHMUCTRANGBI_GIAY = 5
IDDANHMUCTRANGBI_DAI = 6
IDDANHMUCTRANGBI_NON = 7
IDDANHMUCTRANGBI_PHIPHONG = 9
IDDANHMUCTRANGBI_THUCUOI = 10

DANHMUCTRANGBI_MAP = {
    IDDANHMUCTRANGBI_VUKHI: "Vũ khí",
    IDDANHMUCTRANGBI_AO: "Áo",
    IDDANHMUCTRANGBI_PHAPBAO: "Pháp bảo",
    IDDANHMUCTRANGBI_GIAY: "Giày",
    IDDANHMUCTRANGBI_DAI: "Đai",
    IDDANHMUCTRANGBI_NON: "Nón",
    IDDANHMUCTRANGBI_PHIPHONG: "Phi phong",
    IDDANHMUCTRANGBI_THUCUOI: "Thú cưỡi"
}

IDDANHMUCVATTUTIEUHAO_TRANGBI = 0

IDTHUOCTINHVATPHAM_GIAMTRUNGTHUONG = 113
IDTHUOCTINHVATPHAM_GIAMDONGBANG = 106
IDTHUOCTINHVATPHAM_XUATCHIEUVUKHI = 115
IDTHUOCTINHVATPHAM_XUATCHIEUBUAPHAP = 116
IDTHUOCTINHVATPHAM_DANHTAPTRUNG = 146
IDTHUOCTINHVATPHAM_BANGSAT = 123
IDTHUOCTINHVATPHAM_STCBCONGTHEM = 121

TENTHUOCTINH_MAP = {
    IDTHUOCTINHVATPHAM_GIAMTRUNGTHUONG: "Giảm trúng thương",
    IDTHUOCTINHVATPHAM_GIAMDONGBANG: "Giảm đóng băng",
    IDTHUOCTINHVATPHAM_XUATCHIEUVUKHI: "Xuất chiêu vũ khí",
    IDTHUOCTINHVATPHAM_XUATCHIEUBUAPHAP: "Xuất chiêu bùa pháp",
    IDTHUOCTINHVATPHAM_DANHTAPTRUNG: "Đánh tập trung",
    IDTHUOCTINHVATPHAM_BANGSAT: "Băng sát",
    IDTHUOCTINHVATPHAM_STCBCONGTHEM: "STCB cộng thêm",
}

IDTRANGTHAINHANVAT_DUNGIM = 2
IDTRANGTHAINHANVAT_DICHUYEN = 3
IDTRANGTHAINHANVAT_TANCONG = 4
IDTRANGTHAINHANVAT_DACHET = 6

IDHEPHAI_GIAPSI = 0
IDHEPHAI_DAOSI = 1
IDHEPHAI_DINHAN = 2

IDDIACHIKYNANG_MAP = {
    IDHEPHAI_GIAPSI: {1: 1, 27: 2, 28: 3, 29: 4, 30: 5, 31: 6, 32: 7, 33: 8, 34: 9, 35: 10, 36: 11, 37: 12, 38: 13, 39: 14, 40: 15, 41: 16, 42: 17, 128: 18},
    IDHEPHAI_DAOSI: {2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16, 18: 17, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 24: 23, 25: 24, 26: 25, 128: 26},
    IDHEPHAI_DINHAN: {135: 1, 118: 2, 450: 3, 451: 4, 452: 5, 453: 6, 454: 7, 455: 8, 456: 9, 457: 10, 458: 11, 43: 12, 44: 13, 45: 14, 46: 15, 47: 16, 48: 17, 49: 18, 50: 19, 51: 20, 128: 21},
}
